---
  - name: Install Tools
    hosts: localhost
    connection: local
    become: yes
    tasks:
      - name: install git
        apt:
          name: git
          state: present
          update_cache: yes
      - name: install jq
        apt:
          name: jq
          state: present
          update_cache: yes
      - name: get oc cli
        get_url:
          url: https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest/openshift-client-linux.tar.gz
          dest: ~/occli.tar.gz
          force: yes
      - name: extract oc and kubectl cli
        unarchive:
          src: ~/occli.tar.gz
          dest: /usr/bin/
          remote_src: True
      - name: install azure cli dependencies
        apt:
          name: ca-certificates, curl, apt-transport-https, lsb-release, gnupg, python3-pip
          state: present
          update_cache: yes
      - name: install microsoft gpg key
        ansible.builtin.apt_key:
          state: present
          url: https://packages.microsoft.com/keys/microsoft.asc
      - name: install azure cli
        apt:
          name: azure-cli
          state: present
          update_cache: yes
  - name: Configure git
    hosts: localhost
    connection: local
    vars_files: ./vars.yaml
    become_user: "{{ ubuntu.username }}"
    tasks:
      - git_config:
          name: user.email
          scope: global
          value: "{{ git.email }}"
      - git_config:
          name: user.name
          scope: global
          value: "{{ git.username }}"
